### ISSUE TITLE
Could a few more examples be added to showcase the "automatically convert any legacy HTML code into Glimmer DSL Ruby code" part?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-xml#4]
Hey there Andy,

On your blog you announced Glimmer DSL for XML recently, e. g.:

"[...] 1.4.0 has been released! It includes a new HTML To Glimmer Converter [...] that can automatically convert any legacy HTML code into Glimmer DSL Ruby code"

If you have some time, could you provide, say, three different examples for "legacy HTML code"?

That is, on the "left side" the HTML code, and on the right side the Glimmer code? And, can the glimmer
code generate that HTML code, too?

Let me explain why I am asking for a few more examples here.

I have an old project that autogenerates HTML, CSS etc...

One todo entry is to take any random .html file on the world wide web, parse it and then convert
this into a structure that could then be used to re-autogenerate that .html file.

I never finished it, though, and perhaps never will - but even then I am curious whether glimmer can
do this, e. g. act as a dual-path converter. At the least for simple .html files, say, anything that glimmer
CURRENTLY already can handle.

This would be quite cool for many reasons, for instance, people could use glimmer to prototype stuff;
or one day glimmer could even autogenerate ALL websites that exist world-wide. :D

As usual please proceed with this as you wish. To limit the number of open issues I suggest this issue
to be closed at the latest in two months (or earlier of course; I wish github issues would have some
in-built auto-close functionality.)

**Comment by AndyObtiva** [comment]
Yes, Glimmer DSL for XML is now a dual path generator. The Ruby file that is created from an HTML file can be run, and it prints HTML back. 

I don’t have the time to provide more than one example. I am not sure what you are missing from the one example that is provided. It has everything. 

You are welcome to play around with the gem and create multiple examples then submit a PR. 

I am closing this issue as I believe the provided example is sufficient. 

If you have specific questions not vague requests, let me know what they are. But only after you tried the Ruby gem for yourself. I don’t  make open source software for lazy people. You have to try and find the answer for yourself first before asking me questions to avoid wasting my time. 

For example, try to run the html_to_glimmer command against your html files and if something does not work out, let me know what happened by sharing error messages if any.
